import React from "react";
import {
  Globe,
  Smartphone,
  Bot,
  Cloud,
  Palette,
  Settings,
  Car,
  Shield,
  Building2,
  Heart,
  Plane,
  Landmark,
  Radio,
  GraduationCap,
  Twitter,
  Linkedin,
  Github,
  Instagram,
  Code2,
  Server,
  Database,
  ShieldCheck,
  Library,
  Cloud as CloudIcon,
} from "lucide-react";

export const siteData = {
  company: {
    name: "SuperSoft",
    tagline: "Building the Future of Software",
    description:
      "SuperSoft is a full-service software engineering company offering cutting-edge solutions across web, mobile, and AI technologies.",
    contact: {
      email: "hello@supersoft.com",
      // Google Voice number — real number is never exposed
      phone: "+1 (555) 987-6663",
      address: "123 Tech Street, Silicon Valley, CA 94025",
    },
  },
  hero: {
    title: "Building the Future of Software",
    subtitle:
      "Transform your ideas into powerful digital solutions with our expert team of engineers and designers.",
    ctaButtons: [
      { text: "Start Your Project", href: "#contact", primary: true },
      { text: "View Our Work", href: "#portfolio", primary: false },
    ],
    animatedTexts: [
      "Web Development",
      "Mobile Apps",
      "AI Solutions",
      "Cloud Architecture",
    ],
  },
  services: [
    {
      id: 1,
      title: "Web Development",
      description:
        "Custom web applications built with modern frameworks and best practices.",
      icon: <Globe className="w-8 h-8 text-white" />,
      technologies: ["Next.js", "React", "Vue.js", "Node.js", "TypeScript"],
      features: [
        "Progressive Web Apps",
        "E-commerce Platforms",
        "Enterprise Solutions",
        "API Development",
      ],
    },
    {
      id: 2,
      title: "Mobile Development",
      description:
        "Native and cross-platform mobile applications for iOS and Android.",
      icon: <Smartphone className="w-8 h-8 text-white" />,
      technologies: ["React Native", "Expo", "Flutter", "Swift", "Kotlin"],
      features: [
        "iOS & Android Apps",
        "Cross-Platform Solutions",
        "App Store Deployment",
        "Push Notifications",
      ],
    },
    {
      id: 3,
      title: "AI & Agents",
      description:
        "Cutting-edge AI solutions powered by machine learning and large language models.",
      icon: <Bot className="w-8 h-8 text-white" />,
      technologies: [
        "OpenAI APIs",
        "TensorFlow",
        "PyTorch",
        "LangChain",
        "Vector Databases",
      ],
      features: [
        "ChatGPT Integration",
        "Custom AI Agents",
        "ML Models",
        "Data Analytics",
      ],
    },
    {
      id: 4,
      title: "Cloud & DevOps",
      description:
        "Scalable cloud infrastructure and automated deployment pipelines.",
      icon: <Cloud className="w-8 h-8 text-white" />,
      technologies: ["AWS", "Azure", "Google Cloud", "Docker", "Kubernetes"],
      features: [
        "Cloud Migration",
        "CI/CD Pipelines",
        "Infrastructure as Code",
        "Monitoring",
      ],
    },
    {
      id: 5,
      title: "UI/UX Design",
      description: "Beautiful, user-centered designs that delight and convert.",
      icon: <Palette className="w-8 h-8 text-white" />,
      technologies: ["Figma", "Adobe XD", "Sketch", "Framer", "Prototyping"],
      features: [
        "Design Systems",
        "User Research",
        "Prototyping",
        "Brand Identity",
      ],
    },
    {
      id: 6,
      title: "Custom Software",
      description:
        "Tailored enterprise solutions to solve your unique business challenges.",
      icon: <Settings className="w-8 h-8 text-white" />,
      technologies: [".NET", "Java", "Python", "Ruby", "Go"],
      features: [
        "Enterprise Software",
        "SaaS Platforms",
        "ERP Systems",
        "API Integration",
      ],
    },
  ],
  industries: [
    {
      id: 1,
      name: "Automotive",
      description:
        "Connected vehicle platforms, infotainment systems, and smart home integration for the automotive industry.",
      icon: <Car className="w-6 h-6" />,
      projects: 3,
    },
    {
      id: 2,
      name: "Safety & IoT",
      description:
        "Mission-critical safety applications with real-time monitoring and emergency automation systems.",
      icon: <Shield className="w-6 h-6" />,
      projects: 1,
    },
    {
      id: 3,
      name: "Enterprise",
      description:
        "Large-scale consumer platforms for enterprise clients with BLE access, payments, and shared user management.",
      icon: <Building2 className="w-6 h-6" />,
      projects: 1,
    },
    {
      id: 4,
      name: "Healthcare",
      description:
        "HIPAA-compliant patient engagement platforms with EMR integration and secure messaging.",
      icon: <Heart className="w-6 h-6" />,
      projects: 1,
    },
    {
      id: 5,
      name: "Aviation",
      description:
        "Mission-critical flight operations and crew management systems for major airlines.",
      icon: <Plane className="w-6 h-6" />,
      projects: 1,
    },
    {
      id: 6,
      name: "Government",
      description:
        "Cross-platform government applications with multilingual support for public sector deployments.",
      icon: <Landmark className="w-6 h-6" />,
      projects: 1,
    },
    {
      id: 7,
      name: "Telecom",
      description:
        "Large-scale telecom mobile applications including directories and nationwide deployment.",
      icon: <Radio className="w-6 h-6" />,
      projects: 1,
    },
    {
      id: 8,
      name: "Education",
      description:
        "Multi-platform education solutions with digital signage and real-time K-12 district services.",
      icon: <GraduationCap className="w-6 h-6" />,
      projects: 1,
    },
  ],
  stats: [
    { number: 10, suffix: "+", label: "Products Shipped" },
    { number: 20, suffix: "+", label: "Combined Team Years" },
    { number: 5, suffix: "+", label: "Enterprise Clients" },
    { number: 4, suffix: "+", label: "Countries" },
  ],
  portfolio: [
    {
      id: 1, title: "GM HomeBridge", subtitle: "Connected Vehicle Smart Home",
      description: "Android Automotive smart home control platform enabling drivers to operate garage doors, locks, lights, and dimmers from their vehicle. Features a custom Python + Quarkus microservices cloud reducing service costs vs third-party providers.",
      category: "Automotive", technologies: ["Android Automotive", "Python", "Quarkus", "SmartThings", "Google Home"],
      platforms: ["Android Automotive"], client: "General Motors", featured: true, href: "#",
      highlights: ["Garage, lock, light & dimmer integration", "SmartThings & Google Home connectivity", "Custom cloud to reduce service costs"],
    },
    {
      id: 2, title: "GM MyBrand Consumer Apps", subtitle: "Chevrolet · GMC · Cadillac · Buick",
      description: "React Native mobile apps for four of General Motors' flagship vehicle brands — fleet and personal garage management, real-time vehicle status, remote commands, and service scheduling.",
      category: "Automotive", technologies: ["React Native", "iOS", "Android"],
      platforms: ["iOS", "Android"], client: "General Motors", featured: true, href: "#",
      highlights: ["Fleet and My Garage management", "Remote vehicle commands (lock/unlock, start)", "Performance-optimized mobile architecture"],
    },
    {
      id: 3, title: "Volcon Stag – EV App", subtitle: "Connected Electric Vehicle Experience",
      description: "Full-featured connected vehicle app for the Volcon Stag electric UTV. Real-time charge status, charging station locator, and Level 1/2 charge planning.",
      category: "Automotive", technologies: ["React Native", "iOS", "Android"],
      platforms: ["iOS", "Android"], client: "Volcon", featured: false, href: "#",
      highlights: ["Vehicle controls & real-time telemetry", "Charging station locator", "Monitor and plan charging sessions"],
    },
    {
      id: 4, title: "OnStar Guardian", subtitle: "Emergency Automation Platform",
      description: "High-reliability SwiftUI safety app for automatic crash detection, emergency SOS dispatch without user interaction, and live family location tracking.",
      category: "Safety & IoT", technologies: ["SwiftUI", "iOS", "Android", "OnStar API"],
      platforms: ["iOS", "Android"], client: "General Motors / OnStar", featured: false, href: "#",
      highlights: ["Crash detection automation", "Emergency SOS without user action", "Live family tracking & roadside assist"],
    },
    {
      id: 5, title: "Public Storage App", subtitle: "Enterprise Consumer Storage Platform",
      description: "End-to-end consumer app for the world's largest self-storage company — BLE gate/door/elevator access, Apple Pay payments, and shared user access management at scale.",
      category: "Enterprise", technologies: ["React Native", "BLE", "Apple Pay", "iOS", "Android", "Apple Watch"],
      platforms: ["iOS", "Android"], client: "Public Storage", featured: true, href: "#",
      highlights: ["BLE gate, door & elevator one-tap access", "Secure payments & Apple Pay", "Shared user access at scale"],
    },
    {
      id: 6, title: "MyMercy", subtitle: "Patient Engagement Platform",
      description: "Comprehensive patient engagement mobile app powered by MyChart/Epic EMR integration — lab results with trend graphs, appointment scheduling, secure provider messaging, and care plan management.",
      category: "Healthcare", technologies: ["React Native", "Epic / MyChart API", "iOS", "Android"],
      platforms: ["iOS", "Android"], client: "Mercy Health", featured: false, href: "#",
      highlights: ["Lab results with visual trend graphs", "Appointment scheduling", "Secure provider messaging"],
    },
    {
      id: 7, title: "American Airlines – Pilot Systems", subtitle: "Enterprise Flight Operations & Crew Tech",
      description: "Mission-critical web and mobile ecosystem for American Airlines flight operations. Includes WebFOS, Crew Check-In web and desktop apps, Mobile CCI/FOS, and OE Tracker for flight attendants.",
      category: "Aviation", technologies: ["Web", "iOS", "Android", "HockeyApp"],
      platforms: ["Web", "iOS", "Android"], client: "American Airlines", featured: true, href: "#",
      highlights: ["Real-time scheduling & operational workflows", "High-availability mission-critical systems", "Web + mobile crew check-in ecosystem"],
    },
    {
      id: 8, title: "UAE Government Platforms", subtitle: "Ministry of Foreign Affairs & Public Services",
      description: "Cross-platform government mobile apps (Ionic, Xamarin, PhoneGap) for the UAE Ministry of Foreign Affairs — visa exemption lookups, dynamic CMS surveys, and multilingual support at public-sector scale.",
      category: "Government", technologies: ["Ionic", "Xamarin", "PhoneGap", "iOS", "Android"],
      platforms: ["iOS", "Android", "Tablet"], client: "UAE Government", featured: false, href: "#",
      highlights: ["Visa lookup for 100+ countries", "Dynamic CMS-driven surveys & forms", "Arabic · English · Urdu support"],
    },
    {
      id: 9, title: "Etisalat Mobile Services", subtitle: "Enterprise Telecom Platform – UAE",
      description: "Large-scale enterprise telecom mobile applications for Etisalat (e&), one of the largest carriers in the Middle East — including a UAE Yellow Pages business directory deployed nationwide.",
      category: "Telecom", technologies: ["iOS", "Android", "PhoneGap"],
      platforms: ["iOS", "Android"], client: "Etisalat / e&", featured: false, href: "#",
      highlights: ["iOS and Android customer platforms", "UAE Yellow Pages directory app", "Large-scale nationwide deployment"],
    },
    {
      id: 10, title: "SchoolCafe TV & Mobile", subtitle: "School Nutrition & Payments Ecosystem",
      description: "Multi-platform school nutrition and payments ecosystem — FireTV digital signage, ChromeBit kiosk displays, and iOS/Android apps for real-time cafeteria menus, balances, and student engagement across K-12 districts.",
      category: "Education", technologies: ["FireTV", "ChromeBit", "React Native", "iOS", "Android"],
      platforms: ["iOS", "Android", "FireTV"], client: "SchoolCafe", featured: false, href: "https://www.schoolcafe.com/",
      highlights: ["FireTV / ChromeBit digital signage", "Real-time cafeteria menus & balances", "High-scale secure education services"],
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Sarah Johnson",
      position: "CTO",
      company: "HealthPlus Medical",
      image: "/images/testimonials/sarah.jpg",
      content:
        "SuperSoft transformed our healthcare platform with their innovative solutions. Their expertise in telemedicine and compliance requirements was invaluable. The new system has improved patient engagement by 300%.",
      rating: 5,
    },
    {
      id: 2,
      name: "Michael Chen",
      position: "CEO",
      company: "FinFlow",
      image: "/images/testimonials/michael.jpg",
      content:
        "Working with SuperSoft was a game-changer for our FinTech startup. They delivered a robust, secure banking app that exceeded our expectations. Their attention to detail and security-first approach is unmatched.",
      rating: 5,
    },
    {
      id: 3,
      name: "Emily Rodriguez",
      position: "Product Manager",
      company: "ShopSmart",
      image: "/images/testimonials/emily.jpg",
      content:
        "SuperSoft's AI integration has revolutionized our e-commerce platform. The personalized recommendations have increased our conversion rate by 45%. Their team is professional, innovative, and always delivers on time.",
      rating: 5,
    },
    {
      id: 4,
      name: "David Kim",
      position: "Founder",
      company: "QuickStart",
      image: "/images/testimonials/david.jpg",
      content:
        "As a startup, we needed speed and quality. SuperSoft delivered our MVP in record time without compromising on functionality. Their agile approach and technical expertise helped us secure funding.",
      rating: 5,
    },
  ],
  team: [
    {
      id: 1,
      name: "Alex Thompson",
      position: "CEO & Founder",
      bio: "Visionary leader with 15+ years in software engineering and business strategy.",
      image: "/images/team/alex.jpg",
      linkedin: "#",
      twitter: "#",
    },
    {
      id: 2,
      name: "Priya Patel",
      position: "CTO",
      bio: "Tech expert specializing in cloud architecture and scalable systems design.",
      image: "/images/team/priya.jpg",
      linkedin: "#",
      twitter: "#",
    },
    {
      id: 3,
      name: "Marcus Williams",
      position: "Head of Design",
      bio: "Creative director passionate about user experience and innovative design systems.",
      image: "/images/team/marcus.jpg",
      linkedin: "#",
      twitter: "#",
    },
    {
      id: 4,
      name: "Lisa Chen",
      position: "VP of Engineering",
      bio: "Engineering leader with expertise in AI/ML and enterprise software development.",
      image: "/images/team/lisa.jpg",
      linkedin: "#",
      twitter: "#",
    },
  ],
  navigation: [
    { name: "Home", href: "#home" },
    { name: "Services", href: "#services" },
    { name: "Industries", href: "#industries" },
    { name: "Portfolio", href: "#portfolio" },
    { name: "About", href: "#about" },
    { name: "Contact", href: "#contact" },
  ],
  footer: {
    quickLinks: [
      { name: "About Us", href: "#about" },
      { name: "Our Services", href: "#services" },
      { name: "Portfolio", href: "#portfolio" },
      { name: "Contact", href: "#contact" },
    ],
    services: [
      { name: "Web Development", href: "#web-development" },
      { name: "Mobile Apps", href: "#mobile-development" },
      { name: "AI Solutions", href: "#ai-solutions" },
      { name: "Cloud Services", href: "#cloud-services" },
    ],
    industries: [
      { name: "Healthcare", href: "#healthcare" },
      { name: "FinTech", href: "#fintech" },
      { name: "E-commerce", href: "#ecommerce" },
      { name: "Education", href: "#education" },
    ],
    social: [
      { name: "Twitter", href: "#", icon: <Twitter className="w-5 h-5" /> },
      { name: "LinkedIn", href: "#", icon: <Linkedin className="w-5 h-5" /> },
      { name: "GitHub", href: "#", icon: <Github className="w-5 h-5" /> },
      { name: "Instagram", href: "#", icon: <Instagram className="w-5 h-5" /> },
    ],
  },
  contact: {
    title: "Ready to Transform Your Ideas into Reality?",
    subtitle:
      "Let's discuss how we can help bring your vision to life with our expert software engineering services.",
    cta: "Start Your Project",
    email: "hello@supersoft.com",
    // Google Voice number displayed publicly — real number stays private
    phone: "+1 (555) 987-6663",
    address: "123 Tech Street, Silicon Valley, CA 94025",
    officeLocations: [
      "Silicon Valley, CA",
      "New York, NY",
      "London, UK",
      "Singapore",
    ],
  },
  techStack: {
    categories: [
      { id: "all", label: "All" },
      { id: "frontend", label: "Frontend" },
      { id: "backend", label: "Server Side" },
      { id: "database", label: "Databases" },
      { id: "devsecops", label: "DevSecOps" },
      { id: "libraries", label: "Libraries" },
    ],
    items: [
      { name: "React", category: "frontend", icon: "⚛️" },
      { name: "Next.js", category: "frontend", icon: "▲" },
      { name: "Vue.js", category: "frontend", icon: "💚" },
      { name: "Angular", category: "frontend", icon: "🅰️" },
      { name: "TypeScript", category: "frontend", icon: "📘" },
      { name: "Tailwind CSS", category: "frontend", icon: "🎨" },
      { name: "HTML5", category: "frontend", icon: "🌐" },
      { name: "CSS3", category: "frontend", icon: "🎯" },
      { name: "Node.js", category: "backend", icon: "💚" },
      { name: "Python", category: "backend", icon: "🐍" },
      { name: "Go", category: "backend", icon: "🔵" },
      { name: "Rust", category: "backend", icon: "🦀" },
      { name: "Java", category: "backend", icon: "☕" },
      { name: "Ruby", category: "backend", icon: "💎" },
      { name: ".NET", category: "backend", icon: "🔷" },
      { name: "PHP", category: "backend", icon: "🐘" },
      { name: "PostgreSQL", category: "database", icon: "🐘" },
      { name: "MongoDB", category: "database", icon: "🍃" },
      { name: "Redis", category: "database", icon: "🔴" },
      { name: "MySQL", category: "database", icon: "🐬" },
      { name: "Firebase", category: "database", icon: "🔥" },
      { name: "DynamoDB", category: "database", icon: "📦" },
      { name: "Docker", category: "devsecops", icon: "🐳" },
      { name: "Kubernetes", category: "devsecops", icon: "☸️" },
      { name: "AWS", category: "devsecops", icon: "☁️" },
      { name: "Azure", category: "devsecops", icon: "🔷" },
      { name: "Terraform", category: "devsecops", icon: "🏗️" },
      { name: "GitHub Actions", category: "devsecops", icon: "⚡" },
      { name: "Framer Motion", category: "libraries", icon: "🎬" },
      { name: "Redux", category: "libraries", icon: "🔄" },
      { name: "GraphQL", category: "libraries", icon: "◈" },
      { name: "Three.js", category: "libraries", icon: "🧊" },
      { name: "Lodash", category: "libraries", icon: "🔧" },
      { name: "React Native", category: "libraries", icon: "📱" },
    ],
  },
  clientLogos: [
    "Google", "Microsoft", "Amazon", "Salesforce", "Meta",
    "Netflix", "Stripe", "Shopify", "Slack", "Figma",
    "Spotify", "Airbnb", "Uber", "Notion", "Vercel",
  ],
  insights: [
    {
      id: 1,
      type: "Case Study",
      title: "US Fashion Resale Platform Scales to 100K Monthly Transactions",
      description: "How we built a scalable marketplace handling 100K+ transactions per month with real-time inventory.",
      image: null,
      href: "#",
      category: "E-commerce",
    },
    {
      id: 2,
      type: "Blog",
      title: "How Cloud Computing Can Transform Small Businesses",
      description: "Exploring the impact of cloud infrastructure on business scalability and cost efficiency.",
      image: null,
      href: "#",
      category: "Cloud",
    },
    {
      id: 3,
      type: "Blog",
      title: "Custom Web Application Development: Everything You Need to Know",
      description: "A comprehensive guide to building custom web applications for your business needs.",
      image: null,
      href: "#",
      category: "Web Development",
    },
    {
      id: 4,
      type: "Blog",
      title: "How Generative AI is Transforming Business Operations",
      description: "Real-world applications of generative AI across industries and what it means for your business.",
      image: null,
      href: "#",
      category: "AI",
    },
  ],
  partnerships: [
    { name: "Microsoft", icon: "🪟" },
    { name: "AWS", icon: "☁️" },
    { name: "Google Cloud", icon: "🔍" },
    { name: "Salesforce", icon: "☁️" },
    { name: "Shopify", icon: "🛍️" },
    { name: "Docker", icon: "🐳" },
  ],
};
